OASys/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('students/', include('students.urls', namespace='students')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, reverse, reverse_lazy
from django.conf.urls import url
from . import views
from django.contrib.auth.views import(
										LoginView,
										LogoutView,
										PasswordResetView,
										PasswordResetDoneView,
										PasswordResetConfirmView,
										PasswordResetCompleteView,
									)

app_name = "accounts"

urlpatterns = [
	path('', views.home,name='home'),
	path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
	path('register/', views.register,name='register'),
	path('profile/', views.view_profile,name='view_profile'),
	path('profile/edit', views.edit_profile, name='edit_profile'),
	path('change_password/', views.change_password, name='change_password'),
	path('reset_password', PasswordResetView.as_view(template_name='accounts/reset_password.html', email_template_name='accounts/password_reset_email.html',success_url = reverse_lazy('accounts:password_reset_done')), name='reset_password'),
	path('reset_password/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
	# path(r'reset_password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',success_url = reverse_lazy('accounts:password_reset_complete')),name='password_reset_confirm'),
	path('reset_password/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete')
]

students/urls.py
from django.urls import path, reverse, reverse_lazy
from django.conf.urls import url
from . import views

app_name = "students"

urlpatterns = [
	path('assignments/', views.student_asmt, name='assignments'),
]

students/models.py
from django.db import models
from cuser.models import CUser
from OASys import settings
import datetime
from accounts.models import StudentProfile

# Create your models here.
class Subjects(models.Model):
 	subj_id = models.CharField(default='',primary_key=True,max_length=50)
 	name = models.CharField(default='',max_length=200)
 	sub_sem = models.CharField(
						max_length=10,
						choices=(
							('Sem-I','Semester One'),
							('Sem-II','Semester Two'),
							('Sem-III','Semester Three'),
							('Sem-IV','Semester Four'),
							('Sem-V','Semester Five'),
							('Sem-VI','Semester Six'),
						)
					)
 	course = models.CharField(
							max_length=3,
							choices=(
								('MCS','Masters in Computer Science'),
								('MCA', 'Masters in Comuter Applications'),
							)
						)
 	def __str__(self):
 		return self.subj_id

class Teaches(models.Model):
	cid = models.OneToOneField(Subjects, on_delete=models.CASCADE)
	teacher_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	class Meta:
		unique_together = (('cid','teacher_id'),)

	def __str__(self):
		return self.cid.name

class Assignment(models.Model):
	teacher_id = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default='')
	subject = models.ForeignKey(Subjects, on_delete=models.CASCADE)
	asmt_no = models.PositiveSmallIntegerField()
	announcement_date = models.DateField()
	due_datetime = models.DateTimeField()
	asmt_group = models.PositiveSmallIntegerField()
	asmt_file = models.FileField(upload_to='asmt/')
	
	class Meta:
		unique_together = (('subject','asmt_no',),)

	def __str__(self):
		return self.subject.subj_id + "_" + str(self.asmt_no) +"_"+ str(self.announcement_date.year)


class Mark(models.Model):
	asmt = models.ForeignKey(Assignment, on_delete=models.CASCADE)
	student_id = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
	marks = models.PositiveSmallIntegerField()

class Submission(models.Model):
	student_id = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
	asmt = models.ForeignKey(Assignment, on_delete=models.CASCADE)
	submission_datetime = models.DateTimeField()
	asmt_solution_file = models.FileField(upload_to='asmt_submission/')

students/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from accounts.forms import (
							RegisterationForm,
							EditProfileForm,
							StudentProfileForm,
						)
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import Assignment


def student_asmt(request):
	asmts = Assignment.objects
	return render(request, 'students/view_student_asmt.html',{'asmts':asmts})

students/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/botstrap/3.3.7/js/bootstrap.min.js"></script>
	{% block head %}
	<title>Base</title>
	{%  endblock %}
</head>
<body>
		<!-- Static navbar -->
	<br>
	<div class="container center-div">
	    <nav class="navbar navbar-default">
	      <div class="container-fluid">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="{% url 'accounts:home' %}">OASys</a>
	        </div>
	        <div id="navbar" class="navbar-collapse collapse">

	        {%  if user.is_authenticated %}
	          <ul class="nav navbar-nav navbar-left">
	          	<li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>

	            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>

	            <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>

	            <li><a href="{% url 'accounts:home' %}">Home</a></li>

	            <li><a href="{% url 'students:assignments' %}">Assignments</a></li>
	          </ul>

	        {% else %} 
	          <ul class="nav navbar-nav navbar-right">
	          	<li><a href="{% url 'accounts:login' %}">Login</a></li>
	            <li><a href="{% url 'accounts:register' %}">Register</a></li>
	          </ul>

	        {% endif %}
	        </div><!--/.nav-collapse -->
	      </div>
	    </nav>
    </div>
	{% block body %}
	<title>Base</title>
	{%  endblock %}
</body>
</html>