OASys/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('students/', include('students.urls', namespace='students')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, reverse, reverse_lazy
from django.conf.urls import url
from . import views
from django.contrib.auth.views import(
										LoginView,
										LogoutView,
										PasswordResetView,
										PasswordResetDoneView,
										PasswordResetConfirmView,
										PasswordResetCompleteView,
									)

app_name = "accounts"

urlpatterns = [
	path('', views.home,name='home'),
	path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
	path('register/', views.register,name='register'),
	path('profile/', views.view_profile,name='view_profile'),
	path('profile/edit', views.edit_profile, name='edit_profile'),
	path('change_password/', views.change_password, name='change_password'),
	path('reset_password', PasswordResetView.as_view(template_name='accounts/reset_password.html', email_template_name='accounts/password_reset_email.html',success_url = reverse_lazy('accounts:password_reset_done')), name='reset_password'),
	path('reset_password/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
	# path(r'reset_password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',success_url = reverse_lazy('accounts:password_reset_complete')),name='password_reset_confirm'),
	path('reset_password/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete')
]

accounts/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.db.models.signals import post_save
from OASys import settings
from cuser.models import CUser
# Create your models here.
class StudentProfile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	course = models.CharField(
							max_length=3,
							choices=(
								('MCS','Masters in Computer Science'),
								('MCA', 'Masters in Comuter Applications')
							)
						)
	rollno = models.IntegerField(default=0)
	semester = models.CharField(
							max_length=10,
							choices=(
								('Sem-I','Semester One'),
								('Sem-II','Semester Two'),
								('Sem-III','Semester Three'),
								('Sem-IV','Semester Four'),
								('Sem-V','Semester Five'),
								('Sem-VI','Semester Six'),
								)
							)

	def __str__(self):
		return self.user.email

	def full_name(self):
		return self.user.first_name+' '+self.user.last_name


def create_profile(sender, **kwargs):
	if kwargs['created']:
		student_profile = StudentProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=CUser)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from cuser.forms import AuthenticationForm, UserCreationForm
from OASys import settings
from cuser.models import CUser
from accounts.models import StudentProfile
from django.forms import ModelForm

class RegisterationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = CUser
		fields = (
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2',
			'role',
		)
	def save(self, commit=True):
		
		# if RegisterationForm.is_valid(self):
		user = super(RegisterationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

class EditProfileForm(UserChangeForm):

	class Meta:
		model = CUser
		fields = (
			'email',
			'first_name',
			'last_name',
		)

class StudentProfileForm(ModelForm):
	class Meta:
		model = StudentProfile
		fields = ['course','semester','rollno']

accounts/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from accounts.forms import (
							RegisterationForm,
							EditProfileForm,
							StudentProfileForm,
						)
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
	return render(request, 'accounts/home.html')

def register(request):
	if request.method == 'POST':
		form = RegisterationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/accounts/profile')
		else:
			return render(request,'accounts/register.html')
	else:
		form = RegisterationForm()
		args = {'form':form}
		return render(request, 'accounts/register.html', args)

@login_required
def view_profile(request):
	args = {'user': request.user}
	return render(request, 'accounts/view_profile.html', args)

@login_required
def edit_profile(request):
	if request.method == 'POST':
		form = StudentProfileForm(request.POST, instance=request.user)

		if  form.is_valid():
			form.save()
			return redirect('/accounts/profile')

	else:
		form = StudentProfileForm(instance=request.user)
		args = {'form': form, 'user':request.user}
		return render(request, 'accounts/edit_profile.html', args)

@login_required
def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save
			update_session_auth_hash(request,form.user)
			return redirect('/accounts/profile')
		else:
			return redirect('/accounts/change_password')

	else:
		form = PasswordChangeForm(user=request.user)
		args = {'form': form}
		return render(request, 'accounts/change_password.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title> Change Password </title>
	{% endblock %}
</head>

<body>
	{% block body %}
		<form method="post">
			<div class="container">
				{% csrf_token %}
				{{user}}
				{{ form.as_p }}
				<button type="submit">Save Changes</button>
			</div>
		</form> 
	{% endblock %}
</body>
</html>

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title> Edit Profile</title>
	{% endblock %}
</head>

<body>
	{% block body %}
		<form method="post">
			<div class="container">
				{% csrf_token %}
				{{ user }}
				{{ form.as_p }}
				<button type="submit">Save Changes</button>
			</div>
		</form> 
	{% endblock %}
</body>
</html>

accounts/templates/accounts/home.html
{% extends 'base.html' %}

<h1>Home</h1>

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title>Home</title>
	{% endblock %}
</head>
<body>
	{% block body %}

	{% endblock %}
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title>Login</title>
	{% endblock %}
</head>
<body>

	{% block body %}
	<div class="container">
		<p>
			Please Login Here!
		</p>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Login</button>
		</form>
		<a href="{% url 'accounts:reset_password' %}"> Forgot Passsword </a>
	</div>
	{% endblock %}

</body>
</html>s

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title>Login</title>
	{% endblock %}
</head>
<body>

	{% block body %}
	<div class="container">
		<h1>Welcome</h1>
		<p>
			You are Logged Out!<br>
			Please Login Here!
		</p>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Login</button>
		</form>
	</div>
	{% endblock %}

</body>
</html>

accounts/templates/accounts/password_reset_complete.html
<div class="container">
	<br>
	<p>Your password has been set.  You may go ahead and log in now.</p>

	<p><a href="{{ login_url }}">Log in</a></p>

</div>

accounts/templates/accounts/password_reset_confirm.html
{% if validlink %}

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">New password:</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">Confirm password:</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="Change my password">
</fieldset>
</form>

{% else %}

<p>"The password reset link was invalid, possibly because it has already been used.  Please request a new password reset."</p>

{% endif %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title>Reset Password</title>
	{% endblock %}
</head>
<body>

	{% block body %}
	<div class="container">
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly."</p>

		<p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder."</p>

	</div>
	
	{% endblock %}

</body>
</html>

accounts/templates/accounts/password_reset_email.html
 	{% load i18n %}{% autoescape off %}
 	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
 	
	{% trans "Please go to the following page and choose a new password:" %}
 	{% block reset_link %}
 	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
 	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
	{% trans "Thanks for using our site!" %}
	
	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
	{% endautoescape %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block body %}

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title>Register</title>
	{%  endblock %}
</head>
<body>
	<form method="post">
		<div class="container">
			<h1>Register</h1>
			{% csrf_token %}
			{% if form.errors %}
    			{% for field in form %}
        			{% for error in field.errors %}
         			   <div class="alert alert-danger">
                			<strong>{{ error|escape }}</strong>
            			</div>
        			{% endfor %}
    			{% endfor %}
    			{% for error in form.non_field_errors %}
        		<div class="alert alert-danger">
            		<strong>{{ error|escape }}</strong>
        		</div>
    			{% endfor %}
			{% endif %}

			{{ form.as_p }}
			<button type="submit">Register</button>
		</div>
	</form>
</body>
</html>
	
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title>Reset Password</title>
	{% endblock %}
</head>
<body>

	{% block body %}
	<div class="container">
		<p>
			Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
		</p>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Send Instructions</button>
		</form>
	</div>
	{% endblock %}

</body>
</html>s

accounts/templates/accounts/view_profile.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title>Profile</title>
	{% endblock %}
</head>

<body>
	{% block body %}
	{{ user }}
	<br>
	{{user.role}}
	<br>
	{{user.studentprofile.full_name}}
	<br>
	{{user.studentprofile.course}}
	<br>
	{{user.studentprofile.semester}}
	<br>
	{{user.studentprofile.rollno}}
	{% endblock %}
</body>
</html>